### PR TITLE
Fixed a parsing error for some metadata responses

### PR DESCRIPTION
**Pull request by HernanRivasAcosta**

### CODE REVIEW

**Comment by shezarkhani** [comment]
Why haven't you merged this in yet? :) I just tested it and it fixes the bug

**Comment by bigodines** [comment]
+1. would love to see this merged in

**Comment by BunkerSP** [comment]
:+1:  can you please merge this?

**Comment by HernanRivasAcosta** [comment]
I rebased it and need to run the tests. Will merge once that's done.

**Pull request merged**
